spring.application.name=backend

# 1. Chuỗi kết nối đến SQL Server (Thay 'Ten_Database_Cua_Em' bằng tên DB thực tế nhé)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=cinema_db1;encrypt=true;trustServerCertificate=true;

# 2. Tài khoản đăng nhập SQL Server của em (Nếu dùng quyền Windows Auth thì cấu hình kiểu khác, đây là tài khoản SA)
spring.datasource.username=sa
spring.datasource.password=123456

# 3. Khai báo Driver cho SQL Server
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# 4. Cấu hình Hibernate tự động cập nhật bảng (nếu cần) và hiển thị câu lệnh SQL ra Terminal
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect