# =========================================================
# 1. CẤU HÌNH KẾT NỐI DATABASE SUPABASE (POSTGRESQL)
# =========================================================
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
spring.datasource.username=postgres.eoylkjteiudwxxjrsmhc
spring.datasource.password=LasCinema123!

spring.datasource.driver-class-name=org.postgresql.Driver

# =========================================================
# 2. CẤU HÌNH HIBERNATE / JPA
# =========================================================
spring.jpa.properties.spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
spring.jpa.properties.hibernate.format_sql=true
# =========================================================
# 3. CẤU HÌNH CỔNG CHẠY SERVER BACKEND
# =========================================================
server.port=8080

# =========================================================
# 5. CẤU HÌNH GMAIL
# =========================================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=lascinema.system@gmail.com
spring.mail.password=ebzwhfszobtilihz

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=3000
spring.mail.properties.mail.smtp.writetimeout=5000

app.public-url=https://confusing-junkyard-cherub.ngrok-free.dev

# =========================================================
# 6. CẤU HÌNH BACKUP DATABASE (từ nhánh admin)
# =========================================================
app.database.name=cinema_db1
# TODO: đổi lại đường dẫn thư mục backup cho đúng máy đang chạy (đây là path máy của bên admin)
app.backup.directory=D:/DatabaseBackups
